version: '3'
networks: 
  mongo-network:
    external: true
    name: 'mongo-network'
  redis-network:
    external: true
    name: 'redis-network'
  mongo-api-network:
    external: true
    name: 'mongo-api-network'
  

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://admin:password@mongoDB:27017
      - REDIS_URI=redis://redis:6379
      - ENABLE_WRITING_HANDLERS=false
    networks:
      - mongo-api-network
      - redis-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - mongo-api-network
      - mongo-network
    volumes:
      - ./database:/data/db
      - ./init:/docker-entrypoint-initdb.d


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - redis-network


  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19 
    restart: always 
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-network
    depends_on:
      - mongodb
